
                   ###################################################################### 加工训练账期近n月基础数据
                    
20220616-10:39:09  开始时间：2022-06-16 10:39:09
20220616-10:39:09  ---- month: 202010
20220616-10:39:09  ---- 参数设置：
                       ---- step: train
                       ---- Info.model_name: 模型示例
                       ---- Info.n_recent: 3
                       ---- Info.Pcase_limit: 1000
                       ---- Info.traintable_ratio: 2
                       ---- Info.Pcumsum_limit: 2
                       ---- Info.timein_count: 500

                   ------------------------------------- 检查各前置表 --------------------------------------------------- 
20220616-10:39:09  检查 kehujingyingbudb.ml_xy_eg_m


Traceback (most recent call last):
  File "D:\Python for Windows\lib\site-packages\IPython\core\interactiveshell.py", line 3296, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-18-627226a0224d>", line 17, in <module>
    base_train[model_name], Info = privy_basedatafun('train', Info, nmg_yaxin=nmg_yaxin)
  File "D:\工作\模型脚本\ModelProject\selfmodule\tablemodule\tablefun.py", line 668, in privy_basedatafun
    field_all = get_field(Info.table_XY).index
  File "D:\工作\模型脚本\ModelProject\selfmodule\toolmodule\datatrans.py", line 356, in get_field
    field = my_sql_fun(sql, method='read', index_col='col_name').data_type
  File "D:\工作\模型脚本\ModelProject\selfmodule\toolmodule\datatrans.py", line 232, in my_sql_fun
    conn1 = psycopg2.connect(dbname=dbname, user=user, password=pwd, port=port, host=host, client_encoding='UTF-8')
  File "D:\Python for Windows\lib\site-packages\psycopg2\__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError
20220616-10:39:22  开始时间：2022-06-16 10:39:22
20220616-10:39:22  ---- month: 202010
20220616-10:39:22  ---- 参数设置：
                       ---- step: train
                       ---- Info.model_name: 模型示例
                       ---- Info.n_recent: 3
                       ---- Info.Pcase_limit: 1000
                       ---- Info.traintable_ratio: 2
                       ---- Info.Pcumsum_limit: 2
                       ---- Info.timein_count: 500

                   ------------------------------------- 检查各前置表 --------------------------------------------------- 
20220616-10:39:22  检查 kehujingyingbudb.ml_xy_eg_m


Traceback (most recent call last):
  File "D:\Python for Windows\lib\site-packages\IPython\core\interactiveshell.py", line 3296, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-19-542d49823be3>", line 1, in <module>
    base_train[model_name], Info = privy_basedatafun('train', Info, nmg_yaxin=nmg_yaxin)
  File "D:\工作\模型脚本\ModelProject\selfmodule\tablemodule\tablefun.py", line 668, in privy_basedatafun
    field_all = get_field(Info.table_XY).index
  File "D:\工作\模型脚本\ModelProject\selfmodule\toolmodule\datatrans.py", line 356, in get_field
    field = my_sql_fun(sql, method='read', index_col='col_name').data_type
  File "D:\工作\模型脚本\ModelProject\selfmodule\toolmodule\datatrans.py", line 232, in my_sql_fun
    conn1 = psycopg2.connect(dbname=dbname, user=user, password=pwd, port=port, host=host, client_encoding='UTF-8')
  File "D:\Python for Windows\lib\site-packages\psycopg2\__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError
20220616-10:51:49  
                   ---- 统计所有模型目标字段分布
20220616-10:51:49  将excel粘贴的长字符串转为DataFrame
20220616-10:51:49      eval: tableXday_desc
20220616-10:51:49      eval: tableXscore_desc
20220616-10:51:49  
                   ------------------------- kehujingyingbudb.ml_target_info_yw_user_m ----------------
20220616-10:51:49  ---- ['模型示例']
20220616-10:51:49  
                   ---- sql语句：
                   select acct_month,
                   count(1) count_all,
                   sum(case when flag_eg=1 then 1 else 0 end) flag_eg
                   from kehujingyingbudb.ml_target_info_yw_user_m
                   group by acct_month
                   order by acct_month



Traceback (most recent call last):
  File "D:\Python for Windows\lib\site-packages\IPython\core\interactiveshell.py", line 3296, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-20-a039138b241e>", line 2, in <module>
    _ = privy_target_stat(sqltype, infos)
  File "D:\工作\模型脚本\ModelProject\selfmodule\binarymodule\privy_stat.py", line 63, in privy_target_stat
    count_stat = my_sql_fun(sql_stat, method='read')
  File "D:\工作\模型脚本\ModelProject\selfmodule\toolmodule\datatrans.py", line 232, in my_sql_fun
    conn1 = psycopg2.connect(dbname=dbname, user=user, password=pwd, port=port, host=host, client_encoding='UTF-8')
  File "D:\Python for Windows\lib\site-packages\psycopg2\__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError
20220616-10:55:08  
                   ---- 统计所有模型目标字段分布
20220616-10:55:08  将excel粘贴的长字符串转为DataFrame
20220616-10:55:08      eval: tableXday_desc
20220616-10:55:08      eval: tableXscore_desc
20220616-10:55:08  
                   ------------------------- kehujingyingbudb.ml_target_info_yw_user_m ----------------
20220616-10:55:08  ---- ['模型示例']
20220616-10:55:08  
                   ---- sql语句：
                   select acct_month,
                   count(1) count_all,
                   sum(case when flag_eg=1 then 1 else 0 end) flag_eg
                   from kehujingyingbudb.ml_target_info_yw_user_m
                   group by acct_month
                   order by acct_month



Traceback (most recent call last):
  File "D:\Python for Windows\lib\site-packages\IPython\core\interactiveshell.py", line 3296, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-21-a039138b241e>", line 2, in <module>
    _ = privy_target_stat(sqltype, infos)
  File "D:\工作\模型脚本\ModelProject\selfmodule\binarymodule\privy_stat.py", line 63, in privy_target_stat
    count_stat = my_sql_fun(sql_stat, method='read')
  File "D:\工作\模型脚本\ModelProject\selfmodule\toolmodule\datatrans.py", line 232, in my_sql_fun
    conn1 = psycopg2.connect(dbname=dbname, user=user, password=pwd, port=port, host=host, client_encoding='UTF-8')
  File "D:\Python for Windows\lib\site-packages\psycopg2\__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError


Traceback (most recent call last):
  File "D:\Python for Windows\lib\site-packages\IPython\core\interactiveshell.py", line 3296, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-22-dc9bd09ea272>", line 2, in <module>
    if start is not None:
NameError: name 'start' is not defined
20220616-10:56:05  将excel粘贴的长字符串转为DataFrame
20220616-10:56:05      eval: tableXday_desc
20220616-10:56:05      eval: tableXscore_desc
20220616-10:56:22  
                   ------------------------- kehujingyingbudb.ml_target_info_yw_user_m ----------------
20220616-10:56:22  ---- ['模型示例']
20220616-10:56:22  
                   ---- sql语句：
                   select acct_month,
                   count(1) count_all,
                   sum(case when flag_eg=1 then 1 else 0 end) flag_eg
                   from kehujingyingbudb.ml_target_info_yw_user_m
                   group by acct_month
                   order by acct_month



Traceback (most recent call last):
  File "D:\Python for Windows\lib\site-packages\IPython\core\interactiveshell.py", line 3296, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-29-18cd41bdc469>", line 19, in <module>
    count_stat = my_sql_fun(sql_stat, method='read')
  File "D:\工作\模型脚本\ModelProject\selfmodule\toolmodule\datatrans.py", line 232, in my_sql_fun
    conn1 = psycopg2.connect(dbname=dbname, user=user, password=pwd, port=port, host=host, client_encoding='UTF-8')
  File "D:\Python for Windows\lib\site-packages\psycopg2\__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError
20220616-10:56:29  
                   ------------------------- kehujingyingbudb.ml_target_info_yw_user_m ----------------
20220616-10:56:40  ---- ['模型示例']
20220616-10:56:50  
                   ---- sql语句：
                   select acct_month,
                   count(1) count_all,
                   sum(case when flag_eg=1 then 1 else 0 end) flag_eg
                   from kehujingyingbudb.ml_target_info_yw_user_m
                   group by acct_month
                   order by acct_month



Traceback (most recent call last):
  File "D:\Python for Windows\lib\site-packages\IPython\core\interactiveshell.py", line 3296, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-35-398c29a467a7>", line 1, in <module>
    count_stat = my_sql_fun(sql_stat, method='read')
  File "D:\工作\模型脚本\ModelProject\selfmodule\toolmodule\datatrans.py", line 232, in my_sql_fun
    conn1 = psycopg2.connect(dbname=dbname, user=user, password=pwd, port=port, host=host, client_encoding='UTF-8')
  File "D:\Python for Windows\lib\site-packages\psycopg2\__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError


Traceback (most recent call last):
  File "D:\Python for Windows\lib\site-packages\IPython\core\interactiveshell.py", line 3296, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-36-154df9ece9a0>", line 1, in <module>
    count_stat = my_sql_fun(sql_stat, method='read')
  File "D:\工作\模型脚本\ModelProject\selfmodule\toolmodule\datatrans.py", line 232, in my_sql_fun
    conn1 = psycopg2.connect(dbname=dbname, user=user, password=pwd, port=port, host=host, client_encoding='UTF-8')
  File "D:\Python for Windows\lib\site-packages\psycopg2\__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError


Traceback (most recent call last):
  File "D:\Python for Windows\lib\site-packages\IPython\core\interactiveshell.py", line 3296, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-37-afede483ef90>", line 1, in <module>
    print(f"\n统计正例样本量：\n{count_stat}")
NameError: name 'count_stat' is not defined


Traceback (most recent call last):
  File "D:\Python for Windows\lib\site-packages\IPython\core\interactiveshell.py", line 3296, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-38-afede483ef90>", line 1, in <module>
    print(f"\n统计正例样本量：\n{count_stat}")
NameError: name 'count_stat' is not defined
20220616-10:57:39  
                   ---- sql语句：
                   select acct_month,
                   count(1) count_all,
                   sum(case when flag_eg=1 then 1 else 0 end) flag_eg
                   from kehujingyingbudb.ml_target_info_yw_user_m
                   group by acct_month
                   order by acct_month

20220616-11:06:03  
                   ---- sql语句：
                   select acct_month,
                   count(1) count_all,
                   模型示例    sum(case when flag_eg='1' then 1 else 0 end) f...
                   dtype: object
                   from kehujingyingbudb.ml_target_info_yw_user_m
                   group by acct_month
                   order by acct_month



Traceback (most recent call last):
  File "D:\Python for Windows\lib\site-packages\IPython\core\interactiveshell.py", line 3296, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-44-398c29a467a7>", line 1, in <module>
    count_stat = my_sql_fun(sql_stat, method='read')
  File "D:\工作\模型脚本\ModelProject\selfmodule\toolmodule\datatrans.py", line 232, in my_sql_fun
    conn1 = psycopg2.connect(dbname=dbname, user=user, password=pwd, port=port, host=host, client_encoding='UTF-8')
  File "D:\Python for Windows\lib\site-packages\psycopg2\__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError
                   Out[45]: 20220616-11:06:25  "\nselect acct_month,\ncount(1) count_all,\n模型示例    sum(case when flag_eg='1' then 1 else 0 end) f...\ndtype: object\nfrom kehujingyingbudb.ml_target_info_yw_user_m\ngroup by acct_month\norder by acct_month\n        "
20220616-11:06:37  
                   ---- sql语句：
                   select acct_month,
                   count(1) count_all,
                   模型示例    sum(case when flag_eg='1' then 1 else 0 end) f...
                   dtype: object
                   from kehujingyingbudb.ml_target_info_yw_user_m
                   group by acct_month
                   order by acct_month

                   Out[47]: 20220616-11:07:12  "\nselect acct_month,\ncount(1) count_all,\n模型示例    sum(case when flag_eg='1' then 1 else 0 end) f...\ndtype: object\nfrom kehujingyingbudb.ml_target_info_yw_user_m\ngroup by acct_month\norder by acct_month\n        "
20220616-11:07:25  
                   ---- sql语句：
                   select acct_month,
                   count(1) count_all,
                   模型示例    sum(case when flag_eg='1' then 1 else 0 end) f...
                   dtype: object
                   from kehujingyingbudb.ml_target_info_yw_user_m
                   group by acct_month
                   order by acct_month

20220616-11:08:03  
                   ---- sql语句：
                   select acct_month,
                   count(1) count_all,
                   sum(case when flag_eg='1' then 1 else 0 end) flag_eg
                   from kehujingyingbudb.ml_target_info_yw_user_m
                   group by acct_month
                   order by acct_month



Traceback (most recent call last):
  File "D:\Python for Windows\lib\site-packages\IPython\core\interactiveshell.py", line 3296, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-53-154df9ece9a0>", line 1, in <module>
    count_stat = my_sql_fun(sql_stat, method='read')
  File "D:\工作\模型脚本\ModelProject\selfmodule\toolmodule\datatrans.py", line 232, in my_sql_fun
    conn1 = psycopg2.connect(dbname=dbname, user=user, password=pwd, port=port, host=host, client_encoding='UTF-8')
  File "D:\Python for Windows\lib\site-packages\psycopg2\__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError


Traceback (most recent call last):
  File "D:\Python for Windows\lib\site-packages\IPython\core\interactiveshell.py", line 3296, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-62-5ac0ec12ee06>", line 1, in <module>
    conn1 = psycopg2.connect(dbname=dbname, user=user, password=pwd, port=port, host=host, client_encoding='UTF-8')
  File "D:\Python for Windows\lib\site-packages\psycopg2\__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError
                   Out[63]: 20220616-11:09:43  'postgres'
                   Out[64]: 20220616-11:09:47  'postgres'
                   Out[65]: 20220616-11:09:50  'xingjing'
                   Out[66]: 20220616-11:10:04  'xingjing'
                   Out[67]: 20220616-11:11:14  
                   {'dbname': 'postgres',
                    'user': 'postgres',
                    'pwd': 'xingjing',
                    'port': '5432',
                    'host': 'localhost'}


Exception in thread Thread-2:
Traceback (most recent call last):
  File "D:\Python for Windows\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "D:\Python for Windows\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "D:\Program Files\PyCharm 2021.2.2\plugins\python\helpers\pydev\_pydev_comm\pydev_transport.py", line 64, in _read_forever
    self._read_and_dispatch_next_frame()
  File "D:\Program Files\PyCharm 2021.2.2\plugins\python\helpers\pydev\_pydev_comm\pydev_transport.py", line 37, in _read_and_dispatch_next_frame
    direction, frame = self._read_frame()
  File "D:\Program Files\PyCharm 2021.2.2\plugins\python\helpers\pydev\_pydev_comm\pydev_transport.py", line 45, in _read_frame
    buff = readall(self._socket.recv, 4)
  File "D:\Program Files\PyCharm 2021.2.2\plugins\python\helpers\pydev\_pydev_comm\pydev_io.py", line 110, in readall
    chunk = read_fn(sz - have)
ConnectionResetError: [WinError 10054] 远程主机强迫关闭了一个现有的连接。
