
                   ###################################################################### 加工训练账期近n月基础数据
                    
20220624-15:22:59  开始时间：2022-06-24 15:22:59
20220624-15:22:59  ---- month: 202010
20220624-15:22:59  ---- 参数设置：
                       ---- step: train
                       ---- Info.model_name: 模型示例
                       ---- Info.n_recent: 3
                       ---- Info.Pcase_limit: 1000
                       ---- Info.traintable_ratio: 2
                       ---- Info.Pcumsum_limit: 2
                       ---- Info.timein_count: 500

                   ------------------------------------- 检查各前置表 --------------------------------------------------- 
20220624-15:22:59  检查 kehujingyingbudb.ml_xy_eg_m


Traceback (most recent call last):
  File "<ipython-input-7-462eab4eab6f>", line 22, in <module>
    base_train[model_name], Info = privy_basedatafun('train', Info, nmg_yaxin=nmg_yaxin)
  File "D:\工作\模型脚本\ModelProject\selfmodule\tablemodule\tablefun.py", line 673, in privy_basedatafun
    field_all = get_field(Info.table_XY).index
  File "D:\工作\模型脚本\ModelProject\selfmodule\toolmodule\datatrans.py", line 356, in get_field
    field = my_sql_fun(sql, method='read', index_col='col_name').data_type
  File "D:\工作\模型脚本\ModelProject\selfmodule\toolmodule\datatrans.py", line 232, in my_sql_fun
    conn1 = psycopg2.connect(dbname=dbname, user=user, password=pwd, port=port, host=host, client_encoding='UTF-8')
  File "D:\Python for Windows\lib\site-packages\psycopg2\__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "192.168.100.112", port 5432 failed: Connection timed out (0x0000274C/10060)
	Is the server running on that host and accepting TCP/IP connections?

